#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# agent.set_env("CREATE_MYSQL_USER", data["create_mysql_user"])
agent.set_env("MYSQL_USER_NAME", data.get("mysql_user_name",''))
agent.set_env("MYSQL_USER_DB", data.get("mysql_user_db",''))
password = {"MYSQL_ADMIN_PASS":data["mysql_admin_pass"],"MYSQL_USER_PASS": data.get("mysql_user_pass",'')}
agent.write_envfile("password.env", password)

agent.set_env("CREATE_MYSQL_USER", data.get("create_mysql_user",False))